"""Risk analytics interface built on Neutryx valuation components."""

from __future__ import annotations

from .analytics import (
    RiskEngine,
    RiskFactorAttributionMethod,
    compute_cvar,
    compute_expected_shortfall,
    compute_var,
    explain_pnl,
    generate_historical_scenarios,
    generate_monte_carlo_scenarios,
    generate_standard_stress_scenarios,
    risk_factor_attribution,
    run_scenario_analysis,
    run_stress_test,
    run_stress_tests,
    scenario_expected_shortfall,
)
from .limits import (
    BreachSeverity,
    ConcentrationLimit,
    IssuerLimit,
    Limit,
    LimitBreach,
    LimitManager,
    LimitStatus,
    LimitType,
    NotionalLimit,
    PreTradeCheck,
    VaRLimit,
    WhatIfScenario,
    pre_trade_control,
    what_if_analysis,
)
from neutryx.valuations.pnl_attribution import (
    AttributionMethod,
    MarketState,
    PnLAttribution,
)
from neutryx.valuations.risk_metrics import VaRMethod
from neutryx.valuations.scenarios.scenario_engine import (
    MarketScenario,
    ScenarioResult,
    ScenarioType,
)
from neutryx.valuations.stress_test import HISTORICAL_SCENARIOS, StressScenario
from .sensitivity_analysis import (
    SensitivityConfig,
    SensitivityMethod,
    FiniteDiffScheme,
    PortfolioSensitivity,
    calculate_dv01,
    calculate_cs01,
    calculate_vega_surface,
    calculate_fx_greeks,
    calculate_higher_order_greeks,
    aggregate_portfolio_sensitivities,
    format_sensitivity_report,
    benchmark_sensitivity_methods,
)

__all__ = [
    "RiskEngine",
    "RiskFactorAttributionMethod",
    "AttributionMethod",
    "VaRMethod",
    "MarketScenario",
    "ScenarioResult",
    "ScenarioType",
    "StressScenario",
    "HISTORICAL_SCENARIOS",
    "MarketState",
    "PnLAttribution",
    "compute_var",
    "compute_cvar",
    "compute_expected_shortfall",
    "run_stress_test",
    "run_stress_tests",
    "generate_historical_scenarios",
    "generate_standard_stress_scenarios",
    "generate_monte_carlo_scenarios",
    "run_scenario_analysis",
    "scenario_expected_shortfall",
    "risk_factor_attribution",
    "explain_pnl",
    # Limits and Controls
    "LimitType",
    "LimitStatus",
    "BreachSeverity",
    "Limit",
    "NotionalLimit",
    "VaRLimit",
    "ConcentrationLimit",
    "IssuerLimit",
    "LimitBreach",
    "LimitManager",
    "PreTradeCheck",
    "pre_trade_control",
    "WhatIfScenario",
    "what_if_analysis",
    # Sensitivity Analysis
    "SensitivityConfig",
    "SensitivityMethod",
    "FiniteDiffScheme",
    "PortfolioSensitivity",
    "calculate_dv01",
    "calculate_cs01",
    "calculate_vega_surface",
    "calculate_fx_greeks",
    "calculate_higher_order_greeks",
    "aggregate_portfolio_sensitivities",
    "format_sensitivity_report",
    "benchmark_sensitivity_methods",
]
